baseURL = 'http://www.christianblessing.me/'
#baseURL = 'http://christianblessing-me.github.io/blog/'
languageCode = 'en-us'
title = 'christianblessing.me'
theme = "etch"
publishDir = "docs"

enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  highlight = true
  description = ""
  copyright = ""
  dark = "auto"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "impressum"
    name = "imprint"
    title = "imprint"
    url = "/impressum/"
    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
